name: proba_sdk_flutter
description: Mobile framework for Proba platform.
version: 1.0.0
maintainer: Proba (https://github.com/proba)
homepage: https://proba.com

environment:
  sdk: ">=2.7.0 <2.12.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12
  uuid: ^2.2.2
  http: ^0.12.2
  dart_jsonwebtoken: ^1.6.2
  shake: ^0.1.0
  meta: ^1.1.8
